[package]
name = "tadpole"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tadpole"
path = "src/main.rs"

[features]
default = ["print_persistence_pairs"]
use_coefficients = []
indicate_progress = []
print_persistence_pairs = ["dep:crossterm"]

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = { version = "0.28", optional = true }
